# ?? Servidor ????????????????????????????????????????????
server.port=8080

# ?? Actuator (Spring) ???????????????????????????????????
# Expõe /actuator/health além do nosso /health customizado
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ?? Banco de dados ??????????????????????????????????????
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/devops}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:password}

# ?? JPA ?????????????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# ?? Flyway ??????????????????????????????????????????????
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration